### ISSUE TITLE
I think we should somehow involve the group in the process.

### ISSUE THREAD

**Issue by MElemental** [calebjpicker/TODA#43]
Ian and Ed told me the group doesn't necessarily want to deal with data analysis, but they are interested in designing board games and having discussions about that.

I think we can actually create a parallel structure with the new Clark County School District standards for Engineering Design in Next Generation Science Standards to accomplish both of these goals.

https://drive.google.com/drive/folders/1vRdUr3iWercVJ-JkyFpTdTkXefG9iiuw

**Comment by calebjpicker** [comment]
I think we involved the group in the process last night, and we will be going public by the end of the week.  I suggest we make the parallel structure idea into a new issue.  Perhaps even a new project.

**Comment by MElemental** [comment]
When we post the link we should close this issue.

**Comment by calebjpicker** [comment]
We posted the link, so I'm going to close this issue.
