### ISSUE TITLE
Review and define philosophical pillars and Preamble of TODA

### ISSUE THREAD

**Issue by calebjpicker** [calebjpicker/TODA#47]
Tabletop Organization for Data, Design, and Application
Purpose of TODA—philosophical pillars that can be summarized in one word

**Interdisciplinary and Collaborative**.  Every perspective has value through different analyses. And every analysis generates new value through collaboration.  -- rudy, caleb

**Growth Mindset**.  Knowledge and skills increase through passion and perseverance.  -- rudy, caleb

**Engage and Adapt**.  Involve and develop with the changing needs of the organization and the community.

**Educate and Empower**.  Develop, demonstrate, and parallel new knowledge and skills to increase self-confidence.

Engage. Engage the community in how science and engineering principles.
	Parallel.  Break up false dichotomy between being technical and creative.
	Educating.

Daring. Different. Diverse.
Structure.
Slogan
Design. Test. Play.
Learn.

**Comment by calebjpicker** [comment]
Preamble:
Tabletop games foster a sense of community.  Tabletop games therefore offer the chance to bring together and engage individuals from other disciplines, to collaborate, and to cultivate and explore passions.  Each exploration offers individuals the opportunity to grow their knowledge and skills and as a  result, educate and empower individuals.  Individuals are the nodes that comprise TODA, and thus TODA is designed to grow the individual as well as continually adapt to changing needs.

Please review @MElemental

**Comment by MElemental** [comment]
I think the preamble should be more than just a rehash of our principles. We should try to give a powerful statement.

Preamble:

Tabletop games explore a wide array of themes, passions, and interests.
In 2014, Meeplecon expanded board gaming culture in Las Vegas.
In 2016, Meepleville opened in Las Vegas with a library that demonstrated just how wide these themes, passions, and interests spread. 
An [interview](https://geekandsundry.com/meet-the-comedian-who-opened-a-board-game-cafe-in-sin-city/) with Meepleville's owner stated how much board gaming provides a positive influence to the community, and how reluctant school administrators could not see it's contribution to society.

We form the Tabletop Organization for Data, Design, and Application to demonstrate how the various tabletop games satisfy needs and values in society, and parallel science, engineering, and art.

**Comment by calebjpicker** [comment]
>Tabletop games foster a sense of community.
>Tabletop games therefore offer the chance to bring together and engage individuals from other disciplines, to collaborate, and to cultivate and explore passions.
>Each exploration offers the opportunity for individuals to grow their knowledge and skills and so educate and empower individuals.
>Individuals are the nodes that comprise TODA, and thus TODA is designed to grow the individual as well as continually adapt to changing needs.

>Tabletop games explore a wide array of themes, passions, and interests.
>In 2014, Meeplecon expanded board gaming culture in Las Vegas.
>In 2016, Meepleville opened in Las Vegas with a library that demonstrated just how wide these themes, passions, and interests spread.
>An interview with Meepleville's owner stated how much board gaming provides a positive influence to the community, and how reluctant school administrators could not see it's contribution to society.
>We form the Tabletop Organization for Data, Design, and Application to demonstrate how the various tabletop games satisfy needs and values in society, and parallel science, engineering, and art.

Tabletop games explore a wide array of themes, passions, and interests.  They imbue us with simplicity and complexity, with collaboration and deception, and with strategy and constraint.  Each tabletop game offers individuals the opportunity to explore these themes, to test and develop new values, and to shape and satisfy their needs.

We use tabletop games as the media by which we satisfy society's needs and values.  To best satisfy society's needs, our organization parallels the structure of relationships between science, engineering, and art.  Science collects data to teach us what the needs are and how to best solve them.  Engineering takes what was learned in science to design and apply these changes.  Art provides the medium for expression.  We form Tabletop Organization for Data, Design, and Application to leverage the power of science, engineering, and art so that we may best use tabletop games to satisfy societal needs and values.

**Comment by MElemental** [comment]
The last paragraph is very redundant

**Comment by MElemental** [comment]
Perhaps instead of science engineering  and art we use theory and practice and group the goals of engineering and art under practice

**Comment by MElemental** [comment]
Tabletop games explore a wide array of themes, passions, and interests. From the spatial and computational constraints of physical tabletop games, simple rules generate complex strategies.

Our organization seeks to parallel the interaction between theory, practice and society. Theory involves science and philosophy to generate models of study. Practice involves art and engineering to develop concrete tools and subjects that Theorists may use to advance theory. Together, Theory and Practice,  work together to satisfy and develop societies needs, values and imagination.

**Comment by MElemental** [comment]
> Tabletop games explore a wide array of themes, passions, and interests. From the spatial and computational constraints of physical tabletop games, simple rules generate complex strategies.
> 
> Our organization seeks to parallel the interaction between theory, practice and society. Theory involves science and philosophy to generate models of study. Practice involves art and engineering to develop concrete tools and subjects that Theorists may use to advance theory. Together, Theory and Practice, work together to satisfy and develop societies needs, values and imagination.

This still needs to tie tabletop to theory practice and society

**Comment by calebjpicker** [comment]
> 

> 
> 
> Tabletop games explore a wide array of themes, passions, and interests. From the spatial and computational constraints of physical tabletop games, simple rules generate complex strategies.
> 
> Our organization seeks to parallel the interaction between theory, practice and society. Theory involves science and philosophy to generate models of study. Practice involves art and engineering to develop concrete tools and subjects that Theorists may use to advance theory. Together, Theory and Practice, work together to satisfy and develop societies needs, values and imagination.

Tabletop games explore a wide array of themes, passions, and interests. From the spatial and computational constraints of physical tabletop games, simple rules allow players to construct complex theories and then devise strategies to test those theories.  When tested, players use the collected to revise revise their theories and strategies.  Tabletop games therefore offer players the opportunity construct theories, practice those theories, and advance those theories in a way that meets the players needs at that moment.

At a higher level, our tabletop organization will accommodate and promote the use of theory and practice to satisfy societal values.  We believe that societal values are best determined from the individuals that comprise society.   Therefore, at every level, the individuals dictate organizational needs, and the organization provides the structure to use theory and practice to satisfy those needs.

**Comment by MElemental** [comment]
The last paragraph needs to make clear what theory and practice is. It's a phrase that's used so often that meaning can be vauge

**Comment by MElemental** [comment]
> > 
> 
> > Tabletop games explore a wide array of themes, passions, and interests. From the spatial and computational constraints of physical tabletop games, simple rules generate complex strategies.
> > Our organization seeks to parallel the interaction between theory, practice and society. Theory involves science and philosophy to generate models of study. Practice involves art and engineering to develop concrete tools and subjects that Theorists may use to advance theory. Together, Theory and Practice, work together to satisfy and develop societies needs, values and imagination.
> 
> Tabletop games explore a wide array of themes, passions, and interests. From the spatial and computational constraints of physical tabletop games, simple rules allow players to construct complex theories and then devise strategies to test those theories. When tested, players use the collected data to revise their theories. Tabletop games therefore offer players the opportunity to construct theories, practice those theories, and advance those theories in a way that meets the players needs at that moment.
> 
> At a higher level, our tabletop organization will accommodate and promote the use of theory and practice to satisfy societal values. We believe that societal values are best determined from the individuals that comprise society. Therefore, at every level, the individuals dictate organizational needs, and the organization provides the structure to use theory and practice to satisfy those needs.

Also let's not quite reply with a revision, let's quote reply with a critique, and post a revision as a separate comment.

**Comment by MElemental** [comment]
Tabletop games explore a wide array of themes, passions, and interests. From the spatial and computational constraints of physical tabletop games, simple rules allow players to construct complex theories and then devise strategies to test those theories. When tested, players use the collected data to revise their theories. Tabletop games therefore offer players the opportunity to construct theories, practice those theories, and advance those theories.

At a higher level, our tabletop organization will accommodate and promote the use of theory and practice to satisfy societal needs and values. Individuals of various skills and backgrounds determine societal needs and values. At every level, individuals develop organizational needs, and the organization provides the structure to use theory and practice to satisfy those needs.

**Comment by MElemental** [comment]
> The last paragraph needs to make clear what theory and practice is. It's a phrase that's used so often that meaning can be vauge

I think theory was defined or exemplified explicitly , practice still needs to be defined. I want to make the use of science, philosophy, art and engineering as parallels in this preamble

**Comment by MElemental** [comment]
We have worked on, and discussed this issue and added it to the Constitutional branch.

**Comment by calebjpicker** [comment]
I reopened this.  We should first work on revising your statement and then work on revising the preamble to add:

- collaborative ideas
- growth mindset

then we should also review the pillars again to make sure we've capture enough of those pillars in the preamble.

**Comment by calebjpicker** [comment]
Feedback from Ed, Amina, and Ian on preamble:

Sounds specific to club to be
Better talk about different aspects of board games that people want
Doesn’t sound like there is much room for people to have their interests represented in the club
Give interpersonal talk or seminar, art of teaching 
Flip the point of view from the ‘nodes’ point of view—make user-centric
Given advice about how to write things
	Comes down to how things are narratively phrased
Board games aren’t just board games, they can teach you, playing and using board games

**Comment by calebjpicker** [comment]
We finalized this.  Any additional changes will be made after the rest of the constitution is complete.  I'm closing this issue.
