### ISSUE TITLE
Possible name change: Tabletop organization with Design, Data, and Adventure

### ISSUE THREAD

**Issue by MElemental** [calebjpicker/TODA#63]
application and design are kind of redundant. Adventure would capture a broader set of interests, and put it at the same level as Data and Design. I think it would capture the sense of excitement, learning, and story.

**Comment by calebjpicker** [comment]
This doesn't sound like something where we just play games, and it sounds almost too educational.  We will change the name our organization:

Tabletop Organization
Tabletop Game Society
Tabletop Game Community
Tabletop Gaming Community
Community of Tabletop Gaming
Tabletop Games and Expansions
Community of Tabletop Games and Expansions
Community of Games 'N Intellectual Tabletop InteractiVE

**Comment by MElemental** [comment]
Tabletop Games with Expansions for Life

**Comment by MElemental** [comment]
What are people doing:

Playing Games
Design
Enhance/Improve
Socialize
Compete

TO(E)DA
Tabletop Organization (with) Design and Achievement
Tabletop Organization (with) Daily Achievement
Tabletop Organization: Design Association
Tabletop Organization: 

(T)GAME

**Tabletop Games with Assorted and Malleable Experiences**
Tabletop Gaming Organization for Experiences
(T)GAMES
PODA
TG

**Comment by calebjpicker** [comment]
Tabletop Gaming: Assorted and Malleable Experiences is the official name.  I'm closing this issue.
